plugins {
    id 'com.android.application'
}

android {
    namespace 'com.dafthacker.kb1001perf'
    compileSdk 35

    defaultConfig {
        applicationId 'com.dafthacker.kb1001perf'
        minSdk 29
        targetSdk 35
        versionCode 1
        versionName '0.1-alpha'
    }

    buildTypes {
        release {
            minifyEnabled false
            proguardFiles getDefaultProguardFile('proguard-android-optimize.txt'), 'proguard-rules.pro'
        }
    }
}
