plugins {
    id 'com.android.application'
}

def ciCode = System.getenv("APP_VERSION_CODE")
def ciName = System.getenv("APP_VERSION_NAME")

android {
    namespace 'com.dafthacker.kb1001perf'
    compileSdk 35

    defaultConfig {
        applicationId 'com.dafthacker.kb1001perf'
        minSdk 29
        targetSdk 35
        versionCode ciCode ? ciCode.toInteger() : 3
        versionName ciName ?: '0.3-alpha'
    }

    buildTypes {
        release {
            minifyEnabled false
            proguardFiles getDefaultProguardFile('proguard-android-optimize.txt'), 'proguard-rules.pro'
        }
    }
}
